Library/Library/WebLibrary/Controllers/AuthorController.cs
using Library.BLL.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Library.Entities;
using FluentValidation;
using WebLibrary.Models;
using System.Linq;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace WebLibrary.Controllers
{
    [Authorize(Roles = "admin")]
    public class AuthorController : Controller
    {
        private readonly ILogger<AuthorController> _logger;
        private readonly IAuthorService _authorService;
        public AuthorController(ILogger<AuthorController> logger, IAuthorService authorService)
        {
            _logger = logger;
            _authorService = authorService;
        }

        // GET: AuthorController/Create
        public ActionResult Create()
        {        
            return PartialView(new NewAuthor());
        }

        // POST: AuthorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewAuthor model)
        {
            try
             {
                model.Id = _authorService.InsertAuthor(new Author
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Description = model.Description
                });
                return Created(string.Empty, model);
            }
            catch (ValidationException ex)
            {
                model.ExeptionMessage = ex.Errors.Select(x => x.ErrorMessage).ToList();
                return BadRequest(model.ExeptionMessage);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error when creating a new author.");
                model.ExeptionMessage = new List<string>() { ex.Message };
                return StatusCode(StatusCodes.Status500InternalServerError, model.ExeptionMessage);
            }
        }
    }
}

Library/Library/WebLibrary/Controllers/BookController.cs
using System;
using Library.BLL.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Library.Entities;
using System.Linq;
using FluentValidation;
using System.Collections.Generic;
using WebLibrary.Models.BookModels;
using WebLibrary.Models;
using WebLibrary.Helpers;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace WebLibrary.Controllers
{
    public class BookController : Controller
    {
        private readonly ILogger<BookController> _logger;
        private readonly IBookService _bookService;
        private readonly AuthorSelectItemsHelper _authorHelper;
        private readonly IMapper _mapper;

        public BookController(ILogger<BookController> logger, IBookService bookService, AuthorSelectItemsHelper authorHelper, IMapper mapper)
        {
            _logger = logger;
            _bookService = bookService;
            _authorHelper = authorHelper;
            _mapper = mapper;
        }
        // GET: BookController
        public ActionResult Index()
        {
            var books = _bookService.GetBooks().Select(book => new BookCatalog
            {
                Id = book.Id,
                Title = book.Title,
                City = book.City.Name,
                PublishingOffice = book.PublishingOffice.Name,
                PublishingYear = book.PublishingYear,
                Authors = book.Authors.Select(author => author.FirstName + ' ' + author.LastName).ToList()
            });

            return View(books);
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            List<int> ids = new List<int>(id);
            ids.Add(id);
            Book book = _bookService.GetBooks(ids).FirstOrDefault();
            var bookCatalog = _mapper.Map<BookCatalog>(book);
            return View(bookCatalog);
        }

        // GET: BookController/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            Content(User.Identity.Name);
            return View(new NewBook
            {
                AvailableAuthors = _authorHelper.GetAuthorSelectItems()
            });
        }

        // POST: BookController/Create
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewBook model)
        {
            try
            {
                _bookService.InsertBook(new Book
                {
                    Title = model.Title,
                    ISBN = model.ISBN,
                    PageCount = model.PageCount,
                    Description = model.Description,
                    PublishingYear = model.PublishingYear,
                    City = new City { Name = model.City },
                    PublishingOffice = new PublishingOffice { Name = model.PublishingOffice },
                    Authors = model.Authors.Select(x => new Author { Id = x }).ToList()
                });
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                model.ExeptionMessage = ex.Errors.Select(x => x.ErrorMessage).ToList();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error when creating a new book.");
                model.ExeptionMessage = new List<string>() { ex.Message };
            }
            model.AvailableAuthors = _authorHelper.GetAuthorSelectItems();
            return View(model);
        }

        // GET: BookController/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            try
            {
                List<int> ids = new List<int>(id);
                ids.Add(id);
                Book book = _bookService.GetBooks(ids).FirstOrDefault();
                if (book == null)
                {
                    return NotFound();
                }
                var newBook = _mapper.Map<NewBook>(book);
                newBook.AvailableAuthors = _authorHelper.GetAuthorSelectItems();
                return View(newBook);
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, "Error when editing a book.");
                return StatusCode(StatusCodes.Status500InternalServerError);
            }

        }

        // POST: BookController/Edit/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, NewBook model)
        {
            try
            {
                _bookService.UpdateBook(new Book
                {
                    Id = id,
                    Title = model.Title,
                    ISBN = model.ISBN,
                    PageCount = model.PageCount,
                    Description = model.Description,
                    PublishingYear = model.PublishingYear,
                    City = new City { Name = model.City },
                    PublishingOffice = new PublishingOffice { Name = model.PublishingOffice },
                    Authors = model.Authors.Select(x => new Author { Id = x }).ToList()
                });
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                model.ExeptionMessage = ex.Errors.Select(x => x.ErrorMessage).ToList();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error when editing a book.");
                model.ExeptionMessage = new List<string>() { ex.Message };
            }
            model.AvailableAuthors = _authorHelper.GetAuthorSelectItems();
            return View(model);
        }

        // GET: BookController/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                List<int> ids = new List<int>(id);
                ids.Add(id);
                Book book = _bookService.GetBooks(ids).FirstOrDefault();
                if(book == null)
                {
                    return NotFound();
                }
                var bookCatalog = _mapper.Map<BookCatalog>(book);
                return View(bookCatalog);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error when deletion a book.");
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        // POST: BookController/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, BookCatalog model)
        {
            try
            {
                _bookService.DeleteBook(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error when deletion a book.");
                model.ExeptionMessage = new List<string>() { ex.Message };
                return View(model);
            }
        }
    }
}

Library/Library/WebLibrary/Views/Book/Create.cshtml
@model WebLibrary.Models.NewBook

@{
    ViewData["Title"] = "Create";
    ViewData["FormAction"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>New book</h1>

<hr />

@await Html.PartialAsync("_BookForm", Model)

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/js/authorSelect2.js" asp-append-version="true"></script>
    <script>
        initializeAuthorSelect2('@Url.Action("Create", "Author")');
    </script>
}

Library/Library/WebLibrary/Views/Book/Delete.cshtml
@model WebLibrary.Models.BookModels.BookCatalog

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete book</h1>

<h3>Are you sure you want to delete this book?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishingYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingOffice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishingOffice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Authors)
        </dt>
        <dd class="col-sm-10">
            @foreach (var author in Model.Authors)
            {

                @Html.DisplayFor(model => author)<br>

            }
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
    @{
        if (Model.ExeptionMessage != null)
        {
            foreach (var item in Model.ExeptionMessage)
            {
                <h6 class="text-danger">@item</h6>
            }
        }
    }
</div>

Library/Library/WebLibrary/Views/Book/Details.cshtml
@model WebLibrary.Models.BookModels.BookCatalog

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details book</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PageCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PageCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishingYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingOffice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishingOffice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Authors)
        </dt>
        <dd class="col-sm-10">
            @foreach (var author in Model.Authors)
            {

                @Html.DisplayFor(model => author)<br>

            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

Library/Library/WebLibrary/Views/Book/Edit.cshtml
@model WebLibrary.Models.NewBook

@{
    ViewData["Title"] = "Edit";
    ViewData["FormAction"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit book</h1>

<hr />

@await Html.PartialAsync("_BookForm", Model)

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/js/authorSelect2.js" asp-append-version="true"></script>
    <script>
        initializeAuthorSelect2('@Url.Action("Create", "Author")');
    </script>
}

Library/Library/WebLibrary/Views/Book/Index.cshtml
@model IEnumerable<WebLibrary.Models.BookModels.BookCatalog>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index book</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishingYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishingOffice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Authors)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishingYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishingOffice)
                </td>
                <td>
                    @foreach (var author in item.Authors)
                    {

                        @Html.DisplayFor(modelItem => author)<br>

                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

Library/Library/WebLibrary/Views/Book/_BookForm.cshtml
@model WebLibrary.Models.NewBook

<div class="row">
    <div class="col-md-4">
        <form asp-action="@ViewData["FormAction"]" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PageCount" class="control-label"></label>
                <input asp-for="PageCount" class="form-control" />
                <span asp-validation-for="PageCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingYear" class="control-label"></label>
                <input asp-for="PublishingYear" class="form-control" />
                <span asp-validation-for="PublishingYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingOffice" class="control-label"></label>
                <input asp-for="PublishingOffice" class="form-control" />
                <span asp-validation-for="PublishingOffice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Authors" class="control-label"></label>
                <select class="js-example-basic-multiple" multiple="multiple" asp-for="Authors" asp-items="Model.AvailableAuthors"></select>
                <span asp-validation-for="Authors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" id="createAuthor" value="Create new author" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div id="modDialog" class="modal fade">
            <div id="dialogContent" class="modal-dialog"></div>
        </div>
        @{
            if (Model.ExeptionMessage != null)
            {
                foreach (var item in Model.ExeptionMessage)
                {
                    <h6 class="text-danger">@item</h6>
                }
            }
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>